[project]
name = "deep_learning_playground"
version = "0.1.0"
description = "Add a short description here"
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.11.0.*"
jupyterlab = "*"
matplotlib = "*"
pandas = "*"
numpy = "*"
pip = "*"
tqdm = "*"

[pypi-dependencies]
torch = "*"
torchvision = "*"
torchaudio = "*"
ipywidgets = "*"
wandb = "*"
